### ISSUE TITLE
Dont see spark typenames post installation

### ISSUE THREAD

**Issue by shivsood** [sburn/docker-apache-atlas#11]
Installed ATLAS using this docker image per instructions for 2.0.0. I see lot of assets in UI including hdfs_path, storm_, etc, etc.

![image](https://user-images.githubusercontent.com/1579057/89353658-b5e8d080-d66b-11ea-93ce-3d869bc70710.png)

But i dont see spark_db, spark_table etc. What do a ineed to get spark_db, spark_table etc to show up. Any config? IMO spark model is available in ATLAS 2.0.0 onward. https://issues.apache.org/jira/browse/ATLAS-3214

docker run --detach \
    -p 21000:21000 \
    --name atlas \
    sburn/apache-atlas \
    /opt/apache-atlas-2.0.0/bin/atlas_start.py

Apprecaite any help.

**Comment by sburn** [comment]
Try to run the example (this will add sample types and instances along with traits):

`docker exec -ti atlas tail -f /opt/apache-atlas-2.1.0/bin/quick-start.sh`

**Comment by shivsood** [comment]
Thanks. The commnd worked, but did not create spark_db and spark_table. IMO, spark data model has to be populated by user in ATLAS and it does not come prebuild. I have to check more. Thanks for your help.
