### ISSUE TITLE
Thank you for this repo!

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [sburn/docker-apache-atlas#19]
I just wanted to say thank you for creating this docker image and sharing this repo. I've been trying to setup a docker image myself and ran into numerous complications. It was simple to pull the docker image and follow your quick start instructions.

Thank you for making my job and my life easier :). Kudos to you.

Kurt

**Comment by sburn** [comment]
@kurt-mueller-osumc Thank you for such positive feedback, Kurt! I'm glad you found my work useful.
