### ISSUE TITLE
Return 503 after re-create pod

### ISSUE THREAD

**Issue by wufengzlw** [sburn/docker-apache-atlas#20]
Hi,

Deploy sburn/apache-atlas into kubernetes with PV storage for data and entity:
        volumeMounts:                                                                                                                                                                                              
        - mountPath: /opt/apache-atlas-2.1.0/data                                                                                                                                                                  
          name: atlas-data                                                                                                                                                                                         
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/edge_index_shard1_replica_n1                                                                                                                         
          name: atlas-solr-entity-1                                                                                                                                                                                
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/fulltext_index_shard1_replica_n1                                                                                                                     
          name: atlas-solr-entity-2                                                                                                                                                                                
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/vertex_index_shard1_replica_n1                                                                                                                       
          name: atlas-solr-entity-3                                                                                                                                                                                
        - mountPath: /opt/apache-atlas-2.1.0/solr/server/solr/configsets/_default/conf/managed-schema                                                                                                              
          subPath: managed-schema                                                                                                                                                                                  
          name: managed-schema

The deployment process takes around 15 minutes, then it working fine.

But once I delete the pod and deployment recreate pod, atlas stops working, when I access x.x.x.x:21000, I get 503

**Comment by sburn** [comment]
I haven't tested it under Kubernetes with PV storage and can't help to resolve this issue with your deploy. Sorry.
