### ISSUE TITLE
Typo for quick start script in Readme

### ISSUE THREAD

**Issue by fBedecarrats** [sburn/docker-apache-atlas#22]
The Readme currently reads:
> Run the example (this will add sample types and instances along with traits):
`docker exec -ti atlas /opt/apache-atlas-2.1.0/bin/quick-start.sh`

It should read:
> Run the example (this will add sample types and instances along with traits):
`docker exec -ti atlas /opt/apache-atlas-2.1.0/bin/quick_start.py`

ie. the script is now named **quick_start.py** and not **quick-start.sh**.

Many thanks for this great job!

**Comment by sburn** [comment]
Fixed. Thanks!
