### ISSUE TITLE
Running in docker: Hbase issue

### ISSUE THREAD

**Issue by wufengzlw** [sburn/docker-apache-atlas#24]
Hi,

I run this image in docker(k8s), I met this Hbase issue three times:

- Hbase issue cause port 2181 failed, all connection to this port are refused, this happened twice

- Something wrong with "hbase.regionserver.port", then port 61520 failed, all connection to this port are refused, this happened once

Then I delete pod and it all working properly.

Have you ever met this kind of issue?

Regards,
Liwen Zhao

**Comment by sburn** [comment]
@wufengzlw Container deployment in Kubernetes has not been tested, sorry.

**Comment by wufengzlw** [comment]
Thank you for the reply.

Can I assume that you haven't met this issue with docker deployment?

**Comment by sburn** [comment]
Sorry for the late reply. Yes, there were no such issues with docker deployment. Check Hbase logs.
