### ISSUE TITLE
Error at building from your Dockerfile before changing anything to it

### ISSUE THREAD

**Issue by fBedecarrats** [sburn/docker-apache-atlas#28]
Hello @sburn, thanks again for your great work at building this image. 
I am trying to build upon this repo to provide a francophone interface to the Apache Atlas UI.
I prepared a script that translates the English labels in the html and javascript files located in opt/apache-atlas-2.1.0/webapp/atlas/js/templates and opt/apache-atlas-2.1.0/webapp/atlas/js/views. I made a fork from your repo, and before appending the translation instruction to your Dockerfile, I first tried to build the image from your original dockerfile on Docker hub. Unfortunately, the building process fails, and the logs end with the following error: 
![image](https://user-images.githubusercontent.com/3328347/106363644-06df3600-632a-11eb-98f1-27d6c261cbba.png)
The last line is cropped, it ends with:
![image](https://user-images.githubusercontent.com/3328347/106363659-270ef500-632a-11eb-9c73-524f4d221af2.png)
Do you have an idea of what might cause this error?
Best regards

**Comment by sburn** [comment]
Yeah, one of the latest commits broke this thing. Fixing.

**Comment by fBedecarrats** [comment]
Many thanks for your quick feedback. Bon courage, as we say here.

**Comment by sburn** [comment]
Fixed.

**Comment by fBedecarrats** [comment]
It works great, thank you.
