### ISSUE TITLE
Getting HBASE_CONF_DIR not set error while trying to start docker

### ISSUE THREAD

**Issue by BandeepSingh** [sburn/docker-apache-atlas#3]
Error Log:

Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf')
Traceback (most recent call last):
  File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 191, in <module>
    returncode = main()
  File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 95, in main
    raise Exception("Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir", hbase_conf_dir)
Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf')

**Comment by sburn** [comment]
Provide the full log, please.

**Comment by BandeepSingh** [comment]
Thats the log i get when i run `docker logs atlas`
`Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf')
Traceback (most recent call last):
  File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 191, in <module>
    returncode = main()
  File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 95, in main
    raise Exception("Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir", hbase_conf_dir)
Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf')`

**Comment by sburn** [comment]
How you run it?

**Comment by BandeepSingh** [comment]
Here is the command:
docker run --detach \
    -p 21000:21000 \
    --name atlas \
    sburn/apache-atlas \
    /opt/apache-atlas-2.0.0/bin/atlas_start.py

**Comment by sburn** [comment]
Please send the output of the next command:
`docker exec -it atlas cat /opt/apache-atlas-2.0.0/logs/application.log`

Or. I guess the issue can be caused by the interruption of the first Atlas startup. You may try to start from the beginning by re-creating the container:
`docker stop atlas; docker rm atlas; docker run --detach -p 21000:21000 --name atlas  sburn/apache-atlas /opt/apache-atlas-2.0.0/bin/atlas_start.py`

**Comment by BandeepSingh** [comment]
Output of the command you gave:
Error response from daemon: Container c9ac39aae7f8a1fa401770e39179cd6c1ddac14d644273f3d52959db06b54b23 is not running

Tried stopping/removing and then re-running docker.
Still getting the same error

**Comment by sburn** [comment]
I can't reproduce the issue, container works on my side. Try to run next and copy the output here:
`docker stop atlas; docker rm atlas; docker run --detach -p 21000:21000 --name atlas sburn/apache-atlas /opt/apache-atlas-2.0.0/bin/atlas_start.py && docker exec -it atlas tail -f /opt/apache-atlas-2.0.0/logs/application.log`

**Comment by BandeepSingh** [comment]
Here is the log after excecuting above statement:
atlas
atlas
cee6d7ba6d90a5286546337b3191e883baf10e617a35043af687ea0b88f621d6
cannot exec in a stopped state: unknown

**Comment by sburn** [comment]
Definitely something wrong on your side, a container doesn't even start. Check your system/docker logs.

**Comment by BandeepSingh** [comment]
Still had issues with the docker. 
Most  likely the issue is on my side.

On the flip side, i clone the github repo of Apache Atlas and somehow got the latest apache-atlas-3.0.0-SNAPSHOT working.
However when i try to add new entity, it only shows "hdfs_path" type and nothing else.
Could to help with that regard ?

Thanks

**Comment by BandeepSingh** [comment]
Also, i tried again with a linux machine. 
Still getting the same error from application logs:
`
Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf') Traceback (most recent call last): File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 191, in <module> returncode = main() File "/opt/apache-atlas-2.0.0/bin/atlas_start.py", line 95, in main raise Exception("Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir", hbase_conf_dir) Exception: ('Could not find hbase-site.xml in %s. Please set env var HBASE_CONF_DIR to the hbase client conf dir', '/opt/apache-atlas-2.0.0/hbase/conf')
`

**Comment by sburn** [comment]
I can't reproduce your issue, sorry.

**Comment by sburn** [comment]
I've found the problem and fixed. Check it out.

**Comment by BandeepSingh** [comment]
It worked !
Thanks a lot . .We can close the ticket.

**Comment by sburn** [comment]
Is any data was written into Atlas?
