### ISSUE TITLE
Guidance for API authentication in the Readme file would be helpful

### ISSUE THREAD

**Issue by fBedecarrats** [sburn/docker-apache-atlas#4]
Many thanks for this great image!
I'm struggling to set up correctly set authentication credentials to connect to the REST API. I see in pre-conf/atlas-application.properties that `atlas.authentication.method.kerberos` is set to `false` and that `atlas.authentication.method.file` is set to  `true`. I cannot find the "simple" method mentioned in [the latest version of the Atlas documentation I found](https://atlas.apache.org/1.1.0/Security.html). 
So I guess that the default authentication procedure for your docker image consists in registering a username=group::sha256password string in some credential file. But how should we do that ?
 I see in your readme that you mention an environment variable "ATLAS_PID_DIR" for PID files, but I don't know what to make of it.
Could you please  provide in the readme some indications on how to add/edit users in this setting? That would be very useful to me, and I guess to others.
Best regards

**Comment by sburn** [comment]
Thanks for your feedback! I'll take into account your suggestion for the future.
