### ISSUE TITLE
Errors in script

### ISSUE THREAD

**Issue by krish7919** [sburn/docker-apache-atlas#5]
https://github.com/sburn/docker-apache-atlas/blob/master/atlas_start.py.patch#L19 and https://github.com/sburn/docker-apache-atlas/blob/master/atlas_start.py.patch#L29
seem to be wrongly indented.

**Comment by krish7919** [comment]
In lines https://github.com/sburn/docker-apache-atlas/blob/master/atlas_start.py.patch#L18 and https://github.com/sburn/docker-apache-atlas/blob/master/atlas_start.py.patch#L28: `s/too/to`

**Comment by sburn** [comment]
Fixed.
