### ISSUE TITLE
atlas version 2.1 

### ISSUE THREAD

**Issue by malinc854** [sburn/docker-apache-atlas#7]
Hello,

Can we get image for latest version of atlas release some days back.

Thanks

**Comment by sburn** [comment]
@malinc854 Yes, I'm working on it already.

**Comment by malinc854** [comment]
amazing, thank you. Can we use this for production? are there some consideration if we want to?

**Comment by sburn** [comment]
@malinc854 I'm not sure this type of deployment is production-ready because, first, Atlas is not intended by developers to be run in a container and, second, I haven't tested it in production myself.

**Comment by sburn** [comment]
@malinc854 Atlas 2.1.0 image is available.
