### ISSUE TITLE
Change docker image tag

### ISSUE THREAD

**Issue by hannahkamundson** [sburn/docker-apache-atlas#9]
The update to atlas 2.1.0 was pushed to the docker image 2.0.0. I think it would be beneficial to allow us to still access 2.0.0 for those of us that have built stuff off of that image.

**Comment by sburn** [comment]
@hannahkamundson 2.1.0 pushed to the master and docker image with `latest` tag. Use `2.0.0` tag: `docker pull sburn/apache-atlas`

**Comment by mervayar07** [comment]
> The update to atlas 2.1.0 was pushed to the docker image 2.0.0. I think it would be beneficial to allow us to still access 2.0.0 for those of us that have built stuff off of that image.
